version: '3.8'
services:
  database:
    container_name: BusDB
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: InstrumentalDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432

    restart: always
#указать путь к боту 
  bot_container:
    container_name: BusBot
    build: .
    ports:
      - 8000:8000

    depends_on:
      - database
    restart:
      always
